coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%

flags:
  splunkgate_core:
    paths:
      - packages/splunkgate_core/src/splunkgate_core
  splunkgate_judges:
    paths:
      - packages/splunkgate_judges/src/splunkgate_judges
